mupen64plus/mupen64plus-input-sdl

projects/unix/Makefile
The Mupen64Plus SDL Input plugin is not sensitive to the architecture it's compiled for, only the operating system and the flags used to build it as a plugin and link successfully against a platform's SDL port.
I attach a commit that drops unnecessary architecture checks for this project, which means that new architecture ports have one less project to add a support stanza for in Unix Makefiles.
=> Drop architecture checks for cross-platform project

src/autoconfig.c
This should fix the CID 38117 in Coverity.
Does anyone know how I can find the second bug? The overview page says that there should be two bugs but I can only see one under "Outstanding Defects"
=> Check if the size calculation for config file failed

data/InputAutoCfg.ini
I'm using this receiver: http://www.newegg.com/Product/Product.aspx?Item=9SIA0U008T5260
It identifies as 'Xbox 360 Wireless Receiver (XBOX)', and needed axes 3 and 4 switched from the normal xbox controller config, so I added it as a separate entry.
=> added config for another wireless XBOX receiver

data/InputAutoCfg.ini
This adds a configuration for the Sony Playstation 4 controller (Dualshock 4).
It appears that the name is the same as one of the possible names of the PS3 controller, thus I removed it from the PS3 config.
=> add config for Sony playstation 4 controller

data/InputAutoCfg.ini
Add autoconfig support for Xbox One Wireless Dongle device is listed under [Controller (Xbox One For Windows)]
=> Add autoconfig support for Xbox One Wireless Controller (Dongle)

data/InputAutoCfg.ini
The PLAYSTATION(R)3 Controller was not configured correctly by default, it was configured as a 360 controller.
=> FIX Auto detection of PLAYSTATION(R)3 Controller on OSX

src/plugin.c
Right now, if a USB controller is disconnected during gameplay, it won't ever reconnect. This makes sure that all the controllers are connected using SDL_JoystickGetAttached/SDL_JoystickOpened, if it finds one that is not connected, it attempts to reconnect it.
@richard42 @bsmiles32
=> Re-attach joystick if it has disconnected

data/InputAutoCfg.ini, src/autoconfig.c, src/config.c
This adds supports for ```GetGBCartInfo```. See https://github.com/mupen64plus/mupen64plus-core/pull/337
It also removes the ```plugin``` setting from autoconfig. Right now, if you are using autoconfig, your "plugin" choice is set by the INI file, it shouldn't really be tied to that. So I removed it from the autoconfig settings
=> Don't set "plugin" as part of autoconfig

data/InputAutoCfg.ini
This work best on my distro (Ubuntu 16.04.3 LTS).
The deadzone is very handy for Zelda games, the extra C buttons are indispensable to control Kirby and Jigglypuff in SSB64.
RT (`axis(5+)`) since always been broken, and interrupt LT (`axis(2+)`)... "There can be only one" (Highlander style =P)
=> Fix Microsoft X-Box 360 pad for Linux

src/plugin.c
Right now the default deadzone when mapping an axis to an N64 button is 6000 (out of 32768). This is generally too sensitive. I often find myself pressing the wrong c-button when using the right analog stick for that function.
A deadzone of 16384 (50%) would be more appropriate for the function of a button
=> Increase deadzone for axis->N64 button mappings

README, projects/unix/Makefile, src/autoconfig.c, src/autoconfig.h, src/config.c, src/config.h, src/osal_dynamiclib.h, src/osal_dynamiclib_unix.c, src/osal_dynamiclib_win32.c, src/osal_preproc.h, src/plugin.c, src/plugin.h, src/sdl_key_converter.c, src/sdl_key_converter.h, src/version.h
Linking to the Google Code page isn’t much use anymore.
Across all repos, I changed issue tracker links to the Github tracker, wiki links to the mupen64plus.org wiki, and homepage links to mupen64plus.org.
For the most part I didn’t link to individual repos, for maintenance reasons (if we ever move away from Github, or if we copy files across repos, or…).
=> Update homepage links

data/InputAutoCfg.ini
It is recognized as USB Network Joystick on Windows and as Microntek USB Joystick on Ubuntu
=> Added Multilaser Controller JS030

data/InputAutoCfg.ini
Legit DS4 controllers advertise themselves as Wireless Controller when connected via Bluetooth.
sony 0005:054C:05C4.0043: input,hidraw4: BLUETOOTH HID v81.00 Gamepad [Wireless Controller] on b0:25:9f:d3:8b:d8
=> Recognise DS4 controllers in Bluetooth mode

src/config.c, src/plugin.c, src/plugin.h
Known front-ends have been modified to save configuration after plugin
initialization but before running the game. Now it is no longer
necessary for individual plugins to save their config.
Removing calls to ConfigSaveSection from within plugins makes the
mupen64plus-ui-console '--nosaveoptions' parameter work.
Also remove unused reference to ConfigSaveFile.
=> Remove use of ConfigSaveSection

data/InputAutoCfg.ini
This is a controller I own (https://www.x-kom.pl/p/425872-pad-speedlink-xeox-pro-analog-gamepad-wireless-pc.html) I tested the configuration and it's working good.
=> add tested autoconfig for "Controller (XEOX Gamepad)"

data/InputAutoCfg.ini
- Increase value of AnalogDeadzone by ~75%, because the stick felt too sensitive to me. 
- Increase value of AnalogPeak by ~55% otherwise it will go over the peak and then go in the opposite direction, thus making games unplayable.
- Assign X for Mempak switch and Y for Rumblepak switch, because why not?
Tested on Linux.
=> Fixes for Nintendo Wii Remote Pro Controller autoconfig

projects/msvc/mupen64plus-input-sdl.vcxproj
Example:
`msbuild mupen64plus-input-sdl.vcxproj /p:Configuration=Release;Platform=x64;PlatformToolset=ClangCL`
=> Allow to set custom platform toolset from commands

data/InputAutoCfg.ini
This adds Google Stadia controller support to `InputAutoCfg`. I'd like feedback though on how I've defined buttons.
Here's what a Stadia controller looks like. It works as a normal HID joystick when plugged in via a USB-C (to USB-A in my case) cable. I'm testing on Linux, I'd be curious if this works correctly on Windows or Mac depending how the controller identifies.
First, the straight forward ones:
- The Dpad is mapped to the Dpad
- The center N64 analog stick is mapped to the left analog stick on the Stadia
- The C Button Dpad is mapped to the right analog stick on the Stadia
- Start is mapped to the center Stadia button
- The L and R shoulder triggers are mapped to the Left/Right bumper buttons on the Stadia
The ones I'm unsure of:
- I've mapped the `Z Trig` to the `Y` button (the …
=> Add input config for Google Stadia controller.

data/InputAutoCfg.ini
I am actually not using an Elite Controller. It's what both my revised Xbox One and Series controllers are recognized as (plugged in via cable).
=> Add Xbox One Elite Controller to InputAutoCfg.ini

data/InputAutoCfg.ini
The [Sony Interactive Entertainment Wireless Controller] had incompatible bindings. Z was right analog stick up.
I made a list of the ps4 buttons:
button 0 = cross
button 1 = circle
button 2 = triangle
button 3 = square
button 4 = l1
button 5 = r1
button 6 = l2
button 7 = r2
button 8 = share
button 9 = options
button 10 = ps
button 11 = l3
button 12 = r3
axis 0- = lstick left
axis 0+ = lstick right
axis 1- = lstick up
axis 1+ = lstick down
axis 2+ = l2
axis 2- = l2
axis 3- = rstick left
axis 3+ = rstick right
axis 4- = rstick up
axis 4+ = rstick down
axis 5+ = r2
axis 5- = r2
hat 0 Right = Right
hat 0 Left = Left
hat 0 Down = Down
hat 0 Up = Up
=> Sony PS4 Controller support for linux

data/InputAutoCfg.ini
Limited support due to lacking stick (only 1 D-Pad there). Optimal settings to play Tony Hawk'y Pro Skater 2
=> Add USB controller from PS1 Classic

src/plugin.c, src/plugin.h
The HapticRumble API has been deprecated and controllers (e.g. Xbox One Controller) may fail to rumble using more recent releases of SDL2.
This PR aims to address missing rumble functionality while keeping compatiblity with early SDL2 versions.
=> Update rumble functions for SDL v2.0.18+

data/InputAutoCfg.ini
I was surprised to see mupen not able to auto-config this controller. This fixes that. All the inputs match and works great.
=> Add support for "Xbox Series X Controller"

data/InputAutoCfg.ini
HORIPAD for Nintendo Switch works well with the current Nintendo Switch Pro Controller configuration.
=> add Horipad controller for Nintendo Switch
